# Generated by Django 4.0.2 on 2022-03-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipouser',
            field=models.CharField(choices=[('V', 'Vendedor'), ('C', 'Caixa'), ('A', 'Administrador')], default='V', max_length=1),
        ),
    ]
