# Generated by Django 4.0.2 on 2022-04-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tipouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipouser',
            field=models.CharField(choices=[('V', 'Vendedor'), ('C', 'Caixa'), ('E', 'Estoque'), ('A', 'Administrador')], default='V', max_length=1),
        ),
    ]
