# Generated by Django 4.0.2 on 2022-03-09 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(blank=True, max_length=25, null=True)),
                ('cpf', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=30)),
                ('valor_unitsis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitpro', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('ordem', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=25, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('vendedor', models.CharField(blank=True, max_length=6, null=True)),
                ('nomevendedor', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado')], max_length=1)),
                ('total_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpfvenda', to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Formapagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(choices=[('DH', 'Dinheiro'), ('CC', 'Cartão de Credito'), ('CD', 'Cartão de Débito'), ('DP', 'Deposito em Conta')], max_length=2)),
                ('parcelas', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formpag_venda', to='core.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Corpo_venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripro', models.CharField(blank=True, max_length=30, null=True)),
                ('valor_unitsis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitpro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('codpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_venda', to='core.produto')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_venda', to='core.venda')),
            ],
        ),
    ]
