# Generated by Django 4.0.2 on 2022-04-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_venda_nomevendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='grupo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='corpo_venda',
            name='descripro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
    ]
