# Generated by Django 4.0.2 on 2022-04-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_grupo_alter_corpo_venda_descripro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venda', models.PositiveIntegerField()),
                ('descri', models.CharField(max_length=50)),
                ('visualizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='reposicao',
            field=models.BooleanField(default=False),
        ),
    ]
