# Generated by Django 4.0.2 on 2022-04-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_saidaprodutos_produto_reposicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidaprodutos',
            name='venda',
            field=models.CharField(max_length=10),
        ),
    ]
