# Generated by Django 4.0.2 on 2022-05-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cliente_nome_alter_venda_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpo_venda',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='corpo_venda',
            name='hour_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='hour_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saidaprodutos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='hour_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
