# Generated by Django 4.0.2 on 2022-05-24 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_corpo_venda_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpo_venda',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 5, 24)),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 5, 24)),
        ),
    ]
